function r_dd = f_r_dd(x_dd, z_dd, r, s, r_d, s_d, s_dd, L, g)
    zeta = sqrt(L^2 - r^2 - s^2);
    r_dd = (-r^4 * x_dd - (L^2 - s^2)^2 * x_dd - 2 * r^2 * (s * r_d * s_d + (-L^2 + s^2) * x_dd) ...
    + r^3 * (s_d^2 + s * s_dd^2 - zeta * (g + z_dd)) ...
    + r * (-L^2 * s * s_dd + s^3 * s_dd + s^2 * (r_d^2 - gamma * (g + z_dd)) ...
    + L^2 * (-r_d^2 - s_d^2 + gamma * (g + z_dd)))) / ((L^2 - s^2) * gamma^2);
end

