function s_dd = f_s_dd(y_dd, z_dd, r, s, r_d, s_d, r_dd, L, g)
    zeta = sqrt(L^2 - r^2 - s^2);
    s_dd = (-s^4 * y_dd - (L^2 - r^2)^2 * y_dd - 2 * s^2 * (r * r_d * s_d + (-L^2 + r^2) * y_dd) ...
    + s^3 * (r_d^2 + r * r_dd^2 - zeta * (g + z_dd)) ...
    + s * (-L^2 * r * r_dd + r^3 * r_dd + r^2 * (s_d^2 - gamma * (g + z_dd)) ...
    + L^2 * (-r_d^2 - s_d^2 + gamma * (g + z_dd)))) / ((L^2 - r^2) * gamma^2);
end